import { useState } from "react";
import { createGyapanPreview, fetchGyapanStudents } from "../services/gyapanService";
import "../styles/admin.css";

function GyapanPage() {
  const [date, setDate] = useState(""); const [students, setStudents] = useState([]); const [selected, setSelected] = useState([]); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const back = () => { window.history.pushState({}, "", "/admin/dashboard"); window.dispatchEvent(new PopStateEvent("popstate")); };
  const search = async () => { if (!date) return setError("Select a joined date."); setLoading(true); setError(""); try { const response = await fetchGyapanStudents(date); setStudents(response.students); setSelected([]); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const toggle = (id, checked) => setSelected((current) => checked ? [...current, id] : current.filter((value) => value !== id));
  const generate = async () => { if (!selected.length) return setError("Select at least one student."); setBusy(true); setError(""); try { const response = await createGyapanPreview({ ids: selected }); window.history.pushState({}, "", `/admin/gyapan/${response.gyapan._id}`); window.dispatchEvent(new PopStateEvent("popstate")); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="admin-shell"><header className="admin-topbar"><div><p className="portal-eyebrow">Admin Panel</p><h1>GYAPAN</h1></div><button className="secondary-button" type="button" onClick={back}>Back to Dashboard</button></header><section className="admin-panel"><div className="admin-actions-row"><label className="admin-field certificate-date-filter"><span>Select Date</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button className="primary-button" type="button" onClick={search} disabled={loading}>{loading ? "Searching..." : "Search"}</button></div>{error && <p className="admin-error">{error}</p>}{students.length > 0 && <><div className="admin-actions-row"><label><input type="checkbox" checked={selected.length === students.length} onChange={(event) => setSelected(event.target.checked ? students.map((student) => student._id) : [])} /> Select All</label><span className="admin-muted">{selected.length} selected</span></div><div className="gyapan-cards">{students.map((student) => { const t = student.trainingManagement || {}; return <article className="gyapan-card" key={student._id}><label><input type="checkbox" checked={selected.includes(student._id)} onChange={(event) => toggle(student._id, event.target.checked)} /> {t.studentName || student.name}</label><p>{t.courseName || student.course} · {t.courseYear || student.year}</p><p>{t.branch || student.branch}</p><p>{t.collegeName || student.collegeName}</p><p>{t.collegeLocation || student.location}</p></article>; })}</div><div className="admin-actions-row" style={{ marginTop: 18 }}><button className="primary-button" type="button" disabled={busy} onClick={generate}>{busy ? "Creating Preview..." : "Generate Gyapan"}</button></div></>}{!loading && date && students.length === 0 && !error && <div className="admin-empty-state">No students joined on this date.</div>}</section></main>;
}
export default GyapanPage;
